### PR TITLE
fix: out of bounds read on corrupt extended time

### LINKED ISSUE #86: [BUG] Exception swallowed during initialization -- silently missing data we used to get in 7.4.1
**Describe the bug**
In 7.5.0, the parser is stopping earlier than it did in 7.4.1 without throwing an exception.  The exception is logged, but the client has no idea that there was a problem with the file.

**To Reproduce**
Iterate through the entries...
```
          Archive rar = new Archive(tis.getFile());

            if (rar.isEncrypted()) {
                throw new EncryptedDocumentException();
            }

            FileHeader header = rar.nextFileHeader();
            while (header != null && !Thread.currentThread().isInterrupted()) {
                //DO STUFF
                header = rar.nextFileHeader();
            }
```
**Expected behavior**
Please throw the exception or continue parsing the file as happened in 7.4.1.

**File**
The file is part of our large regression corpus tests over on Apache Tika.  We grabbed this file from Common Crawl.  It is possible that it is truncated.  My Ubuntu package utility does not like the file.  It may actually be corrupted.  We were able to get quite a bit more data out of it with 7.4.1.

https://corpora.tika.apache.org/base/docs/commoncrawl3/3X/3X4JRZZ4TQ2GK4QQDQEXMFCVLM3FM5I4 

**Environment (please complete the following information):**
 - OS: Ubuntu, but not relevant
 - Junrar version: 7.5.0

**Additional context**
Decompiler shows the issue in Archive#setChannel:
```
        try {
            this.readHeaders(length);
        } catch (UnsupportedRarV5Exception | CorruptHeaderException | BadRarArchiveException | UnsupportedRarEncryptedException var6) {
            logger.warn("exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented", var6);
            throw var6;
        } catch (Exception var7) {
            logger.warn("exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented", var7);
        }
```

The exception is:
```
WARN  [main] 19:50:32,239 com.github.junrar.Archive exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented
java.lang.ArrayIndexOutOfBoundsException: 55
	at com.github.junrar.io.Raw.readShortLittleEndian(Raw.java:104) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.rarfile.FileHeader.<init>(FileHeader.java:192) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.readHeaders(Archive.java:439) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.setChannel(Archive.java:198) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.setVolume(Archive.java:778) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.<init>(Archive.java:148) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.<init>(Archive.java:161) ~[junrar-7.5.0.jar:?]
	at org.apache.tika.parser.pkg.RarParser.parse(RarParser.java:75) ~[classes/:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281) ~[classes/:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281) ~[classes/:?]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) ~[classes/:?]
```

### PR DESCRIPTION
**Pull request by andrebrait**
UnRAR never reads more bytes than available in the header
This ports this behavior for parsing of extended time data _only_.

Fixes #86

From UnRAR:
```cpp
ushort RawRead::Get2()
{
  if (ReadPos+1<DataSize)
  {
    ushort Result=Data[ReadPos]+(Data[ReadPos+1]<<8);
    ReadPos+=2;
    return Result;
  }
  return 0;
}
```

### CODE REVIEW

File: src/main/java/com/github/junrar/rarfile/FileHeader.java [hunk 1]
```diff
@@ -642,6 +648,6 @@ public boolean isDirectory() {
      * @since 7.2.0
      */
     public String getFileName() {
-        return isUnicode() ? fileNameW : fileName;
+        return isUnicode() && fileNameW != null && !fileNameW.isEmpty() ? fileNameW : fileName;
```
Comment (gotson) [inline src/main/java/com/github/junrar/rarfile/FileHeader.java:651]: I suppose this is somehow related, as we can have `hasExtTime` while not having actual extended time data, we can have `isUnicode` while not having actual unicode filename ?

Comment (andrebrait) [reply src/main/java/com/github/junrar/rarfile/FileHeader.java:651]: Yes, we can, in theory. If you check the bit of code that fills those fields, you can see `isUnicode()` can be true, but if the length of the decoded string is what's expected, `fileNameW` can be set to an empty string.

Comment (andrebrait) [reply src/main/java/com/github/junrar/rarfile/FileHeader.java:651]: https://github.com/junrar/junrar/blob/622891d137975adab6952fa344096b6ad3955b7c/src/main/java/com/github/junrar/rarfile/FileHeader.java#L151
